spring:
  server:
    forward-headers-strategy: framework
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: SUA_CHAVE_SECRETA_JWT
  expirationMs: 86400000